Develop
JerryOJJ/Property-Pro-Lite pull request #7
Opened 2023-12-26 20:11 UTC by JerryOJJ

Advert and Update pages added

2023-12-29 15:56 UTC, Abobos requested changes

2023-12-29 15:56 UTC, Abobos commented on Advert.html
> +        <form id="form">
Why are you using the attribute `id` here?.. if it is for styling, I will say you keep to class.. so you won't have trouble with[ CSS specificity](https://developer.mozilla.org/en-US/docs/Web/CSS/Specificity).

2023-12-29 15:56 UTC, Abobos commented on SignUp.html
> +        <form id="form" action="User-Page.html">
same here

2023-12-29 15:56 UTC, Abobos commented on UpdateAdvert.html
> +            <form id="form">
```suggestion
            <h3 id="class">Update</h3>
            <form class="form">
```
what do you think?

2023-12-29 15:56 UTC, Abobos commented on UpdateAdvert.html
> +    <script defer src="app.js"></script>
Why are you defering the script?

2023-12-29 15:56 UTC, Abobos commented on home.js
> +function hamFunction() {
What is hamFunction 😆 .. you mean` hamburgerFunction`?

2023-12-29 15:56 UTC, Abobos commented on home.js
> +function hamFunction() {
I even prefer the `toggleMenu`

2023-12-29 15:56 UTC, Abobos commented on media/construction-01.jpg
it will be nice to upload these images to cloudinary and use only the links. like I have mentioned before.

This helps making the image load fast and keep your files free from high size when pushing to github.

2023-12-29 15:58 UTC, Abobos commented
N.B: 
- Always use a nifty PR title
- You are to branch out from develop branch and create a PR from the feature branch to develop

2024-01-01 01:31 UTC, Abobos requested changes
Almost there.

Kindly take.a look at my comments if it makes sense

@JerryOJJ

2024-01-01 01:31 UTC, Abobos commented on Advert.html
> +        <h3 id="title">Post An Property Advert</h3>
There is still `id` here?

2024-01-01 01:31 UTC, Abobos commented on User-Page.js
> +"use strict";
Why are you using `use strict` here?

2024-01-01 01:31 UTC, Abobos commented on app.js
> +"use strict";
Same here?

2024-01-01 01:31 UTC, Abobos commented on home.html
> +      <div id="myLinks">
There is still `id` here.

2024-01-01 01:31 UTC, Abobos commented on miniflat.js
> +  }
What is `php` doing here?

2024-01-02 01:46 UTC, ojjJerry commented on User-Page.js
> +"use strict";
For easier debugging using the console

2024-01-02 01:46 UTC, ojjJerry commented on app.js
> +"use strict";
Yes sir

2024-01-02 01:52 UTC, JerryOJJ commented on User-Page.js
> +"use strict";
For easier debugging using the console

2024-01-02 01:53 UTC, JerryOJJ commented on Advert.html
> +        <h3 id="title">Post An Property Advert</h3>
I'll resolve it

2024-01-02 01:53 UTC, JerryOJJ commented on app.js
> +"use strict";
Yes sir

2024-01-02 01:54 UTC, JerryOJJ commented on home.html
> +      <div id="myLinks">
I'll resolve it

2024-01-02 01:57 UTC, JerryOJJ commented on miniflat.js
> +  }
It's a mistake, I'll resolve it

2024-01-03 15:52 UTC, Abobos commented on User-Page.js
> +"use strict";
👀 .. kindly read about it very well

2024-01-03 15:52 UTC, Abobos commented on home.html
> +      <div id="myLinks">
okay

2024-01-03 15:52 UTC, Abobos approved these changes
LGTM 👍

2024-01-03 16:20 UTC, JerryOJJ commented on User-Page.js
> +"use strict";
Ok sir

2024-01-03 16:22 UTC, merged